name=Logger
version=1.0.0
author=Neal Stephenson
maintainer=Neal Stephenson <nealstep@gmail.com>
sentence=A Simple, well not really, Logging library
paragraph=Define your units, errors, notices, words
category=IO
url=https://github.com/nealstep/ESP32-Logger
architectures=ESP32
